title: GraphQL Ruby
baseurl: "/graphql-ruby-doc-en"
url: "https://rmosolgo.github.io"
source_root: "https://github.com/rmosolgo/graphql-ruby-doc-en"

exclude:
  - .gitignore

keep_files: ["api-doc", ".git"]
# Build settings
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true
  hard_wrap: false
  input: GFM

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

algolia:
  application_id: '8VO8708WUV'
  index_name:     'prod_graphql_ruby'

plugins:
  - jekyll-redirect-from
